### ISSUE TITLE
Exception on the Affl_Accounts__r child relationship name

### ISSUE THREAD

**Issue by dougbennett** [kyleschmid/ObjectMerge#1]
Hey Kyle, 

I'm playing around with this in the sandbox. I'm using the hed__Affiliation__c child object handler looking up to the contact.  I've triple checked the child relationship name, but still doesn't like it.  Attached is full debug log, but the actual exception message below.  Just trying this out for the first time and am interested to see how this goes with HEDA and matching on the child object lookup fields.

Thanks for any help you can provide!

[apex-07L3B000008N9kqUAC.log](https://github.com/kyleschmid/ObjectMerge/files/1661714/apex-07L3B000008N9kqUAC.log)

(257607805)|EXCEPTION_THROWN|[136]|System.QueryException: Didn't understand relationship 'Affl_Accounts__r' in FROM part of query call. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names.

**Comment by kyleschmid** [comment]
@dougbennett Assuming you're using the managed version of HEDA, you'll want to prepend "hed__" to any API names (objects, fields, relationships). I wish Salesforce showed the full API name of the relationship in Setup, but they don't. You can always login to Workbench to see the full thing if you want.

Generally, there are two rules to follow if you're looking at the "Relationship Name" in Salesforce setup:

1. If it is a custom field, the real relationship name has "__r" appended to the end
2. If the field is part of a managed package, the real relationship name has the namespace prepended to the beginning (e.g. "hed__Affl_Accounts__r")

Let me know if adding "hed__" works for you.

**Comment by dougbennett** [comment]
@kyleschmid Thanks very much for that!  I get the __r thing, but the hed namespace wasn't so obvious.  I ran a simple Contact to Affiliation merge and it was great, however the administrative account was not deleted.

I'm a little lost on how this should be set up for a HEDA org.  Are you able to give a very brief overview of how the object merge handlers should be set up for Account, Contact and Affiliation when we want to merge Contacts? We obviously want to delete the administrative accounts but keep the other Accounts and merge the affiliations when a contact is merged.

Thanks for any help you can provide!

**Comment by kyleschmid** [comment]
@dougbennett Deleting the Administrative Account is a bit of an interesting workaround. ObjectMerge doesn't support deleting parent objects, but the Administrative Account is technically both a parent and a child of Contact. HEDA populates the Contact on the Account in the hed__Primary_Contact__c field. If you look at that field, the Child Relationship Name is "Organizations" (API name of hed__Organizations__r). So, if you add a Child Handler for Account with the Child Relationship of hed__Organizations__r and choose "Delete Victim", the Account will be deleted.

The other main consideration when dealing with merging Affiliations is the Program Enrollment object. If you're merging two Affiliations that have Program Enrollments that lookup to them, you'll want to first merge the Program Enrollments and then the Affiliations. This is where the "Order of Execution" field comes in (added late December). You'll need to set Program Enrollments to be merged before Affiliations. You won't have to worry about this if you're not using Program Enrollment or are just deleting them (i.e. if they are coming-in through integration).

P.S.: I'm planning on setting-up Object Merge Handlers for merging Contacts with HEDA and including a .csv in this repo. Just haven't gotten around to it quite yet.

**Comment by dougbennett** [comment]
@kyleschmid Ah yes, the reciprocal relationship with the one2one contact is a good point.  

And now I see where the order of execution comes into play.  We aren't yet using program enrollments but this is a good consideration for other (lookup) junction objects like the affiliation.

This is truly awesome.  Nice work!

**Comment by kyleschmid** [comment]
Thanks!
