### ISSUE TITLE
Unable to Re-Parent ActivityHistory

### ISSUE THREAD

**Issue by skyclan9** [kyleschmid/ObjectMerge#22]
Receiving an error when attempting to re-parent ActivityHistory. It says the WhoId field is editable. Even happens when using clone instead of move. 
Error  message:
ObjectMergePairTrigger: execution of BeforeUpdate caused by: System.SObjectException: Field WhoId is not editable Class.ObjectMergePairTriggerHandler.doMerge: line 228, column 1 Class.ObjectMergePairTriggerHandler.MergeObjects: line 118, column 1 Trigger.ObjectMergePairTrigger: line 33, column 1

**Comment by kyleschmid** [comment]
@skyclan9 It looks like you may have a handler set-up for the unified ActivityHistory object rather than setting up separate handlers for Task and Event. ActivityHistory is read-only and is fed from these two objects.

**Comment by skyclan9** [comment]
@kyleschmid Thank you. This worked.
