### ISSUE TITLE
No such column 'createddate' on entity 'ContentDocumentLink'. - Handle objects without certain fields

### ISSUE THREAD

**Issue by dschach** [kyleschmid/ObjectMerge#24]
I'm guessing that every query includes standard system fields like CreatedDate. But check that each of those fields exists before adding it to the query. Do an object describe and then look for the field in the map keyset.

**Comment by mcp79** [comment]
@dschach It looks like you might be familiar with how this tool actually works for merging contact. Wondering if you could give me feedback on how setup up the handlers for it to successfully merge two contact records?

**Comment by dschach** [comment]
I think the issue here is that some objects don't have CreatedDate fields, for example. So you should do a describe call to get all available fields before adding fields to queries. You've hard-coded some fields (CreatedDate, for example) in a few queries, but that's not best practice.

**Comment by dschach** [comment]
@mcp79 Sounds like you're referencing another issue you created. It's best to keep discussions in their own issues.

@kyleschmid Any thoughts about doing describe calls before creating queries so you can remove hard-coded fields from queries?
