### ISSUE TITLE
Error using the deploy link for Sandbox

### ISSUE THREAD

**Issue by colinkenworthy** [kyleschmid/ObjectMerge#26]
Any idea why it doesn't deploy - using the GitHub deploy link for Sandbox I get this email:

Your request to install package "ObjectMerge 2.2" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: xxxxxxxx (00D1xxxxxxxxxxx)
User: xxxxxxxxx (005xxxxxxxxxxxx)
Package: ObjectMerge (04t0H000000YOey)

Problem:

1.  Missing Organization Feature: CommonPortal null

Thanks,
Colin.

**Comment by kyleschmid** [comment]
@colinkenworthy Try the link now. I just pushed a new version that shouldn't require portal licenses.
