### ISSUE TITLE
Move Victim Standard Action on Affiliation child handler with Primary Affiliations

### ISSUE THREAD

**Issue by dougbennett** [kyleschmid/ObjectMerge#6]
@kyleschmid Hey Kyle, I noticed a problem that I can't seem to get around in my HEDA org.  I also swear I didn't experience this before when I was testing about a month ago.  Here is my scenario:
Contact Parent Handler
Affiliation child handler with Move Victim and Keep Master Actions.

When I merge two Contacts, each with it's own distinct primary Business affiliation (that is, pointing to 2 different business accounts), the HEDA affiliation trigger runs and creates another primary affiliation.  So the master contact now has both original affiliations (desired) plus a new primary affiliation created by the HEDA trigger handler.  This results in duplicate affiliations for the same Business Account.  Also, the new primary affiliation that was created is for the victim Account affiliation and not the master Account affiliation.  It's like it's no longer respecting the Keep Master action and allowing the victim to kick off the HEDA trigger handler.

**Comment by kyleschmid** [comment]
@dougbennett I think this is actually a bug with HEDA. I tested some things out and it seems that when you re-parent any primary Affiliation with a new Contact, HEDA will populate the primary lookup field on the Contact, resulting in an additional primary Affiliation being created and the primary flag on the existing one getting set to false. This may be worth logging an issue on the HEDAP repo for.

**Comment by dougbennett** [comment]
@kyleschmid Ok, thanks for validating that.  I will certainly log an issue in the HEDA repo.
